/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.onlinequizapp.daos;

import java.util.Properties;
import java.util.Random;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import org.onlinequizapp.dtos.UserDTO;

/**
 *
 * @author User-PC
 */
public class EmailDAO {

    //generate vrification code
    public String getRandom() {
        Random rnd = new Random();
        int number = rnd.nextInt(999999);
        return String.format("%06d", number);
    }

    //send email to the user email
    public boolean sendEmail(UserDTO user, String code) {
        boolean test = false;

        String toEmail = user.getEmail();
        String fromEmail = "bossesonlinequiz@gmail.com";
        String password = "onlinequizapp123";

        try {

            // your host email smtp server details
            Properties pr = new Properties();
            pr.setProperty("mail.smtp.host", "smtp.gmail.com");
            pr.setProperty("mail.smtp.port", "587");
            pr.setProperty("mail.smtp.auth", "true");
            pr.setProperty("mail.smtp.starttls.enable", "true");
            pr.put("mail.smtp.socketFactory.port", "587");
            pr.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");

            //get session to authenticate the host email address and password
            Session session = Session.getInstance(pr, new Authenticator() {
                @Override
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(fromEmail, password);
                }
            });

            //set email message details
            Message mess = new MimeMessage(session);

            //set from email address
            mess.setFrom(new InternetAddress(fromEmail));
            //set to email address or destination email address
            mess.setRecipient(Message.RecipientType.TO, new InternetAddress(toEmail));

            //set email subject
            if (user.getVerification() != null) {
                mess.setSubject(user.getVerification() + " - User Email Verification");
            }else{
            mess.setSubject(code + " - User Email Verification");
            }
            //set message text
            //mess.setText("Registered successfully.Please verify your account using this code: " + user.getVerification());
            mess.setContent("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional //EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n"
                    + "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\n"
                    + "<head>\n"
                    + "<!--[if gte mso 9]>\n"
                    + "<xml>\n"
                    + "  <o:OfficeDocumentSettings>\n"
                    + "    <o:AllowPNG/>\n"
                    + "    <o:PixelsPerInch>96</o:PixelsPerInch>\n"
                    + "  </o:OfficeDocumentSettings>\n"
                    + "</xml>\n"
                    + "<![endif]-->\n"
                    + "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n"
                    + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                    + "  <meta name=\"x-apple-disable-message-reformatting\">\n"
                    + "  <!--[if !mso]><!--><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><!--<![endif]-->\n"
                    + "  <title></title>\n"
                    + "  \n"
                    + "    <style type=\"text/css\">\n"
                    + "      table, td { color: #000000; } a { color: #363675; text-decoration: none; }\n"
                    + "@media only screen and (min-width: 620px) {\n"
                    + "  .u-row {\n"
                    + "    width: 600px !important;\n"
                    + "  }\n"
                    + "  .u-row .u-col {\n"
                    + "    vertical-align: top;\n"
                    + "  }\n"
                    + "\n"
                    + "  .u-row .u-col-100 {\n"
                    + "    width: 600px !important;\n"
                    + "  }\n"
                    + "\n"
                    + "}\n"
                    + "\n"
                    + "@media (max-width: 620px) {\n"
                    + "  .u-row-container {\n"
                    + "    max-width: 100% !important;\n"
                    + "    padding-left: 0px !important;\n"
                    + "    padding-right: 0px !important;\n"
                    + "  }\n"
                    + "  .u-row .u-col {\n"
                    + "    min-width: 320px !important;\n"
                    + "    max-width: 100% !important;\n"
                    + "    display: block !important;\n"
                    + "  }\n"
                    + "  .u-row {\n"
                    + "    width: calc(100% - 40px) !important;\n"
                    + "  }\n"
                    + "  .u-col {\n"
                    + "    width: 100% !important;\n"
                    + "  }\n"
                    + "  .u-col > div {\n"
                    + "    margin: 0 auto;\n"
                    + "  }\n"
                    + "}\n"
                    + "body {\n"
                    + "  margin: 0;\n"
                    + "  padding: 0;\n"
                    + "}\n"
                    + "\n"
                    + "table,\n"
                    + "tr,\n"
                    + "td {\n"
                    + "  vertical-align: top;\n"
                    + "  border-collapse: collapse;\n"
                    + "}\n"
                    + "\n"
                    + "p {\n"
                    + "  margin: 0;\n"
                    + "}\n"
                    + "\n"
                    + ".ie-container table,\n"
                    + ".mso-container table {\n"
                    + "  table-layout: fixed;\n"
                    + "}\n"
                    + "\n"
                    + "* {\n"
                    + "  line-height: inherit;\n"
                    + "}\n"
                    + "\n"
                    + "a[x-apple-data-detectors='true'] {\n"
                    + "  color: inherit !important;\n"
                    + "  text-decoration: none !important;\n"
                    + "}\n"
                    + "\n"
                    + "</style>\n"
                    + "  \n"
                    + "  \n"
                    + "\n"
                    + "<!--[if !mso]><!--><link href=\"https://fonts.googleapis.com/css?family=Open+Sans:400,700&display=swap\" rel=\"stylesheet\" type=\"text/css\"><!--<![endif]-->\n"
                    + "\n"
                    + "</head>\n"
                    + "\n"
                    + "<body class=\"clean-body\" style=\"margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #ffffff;color: #000000\">\n"
                    + "<a href=\"file:///C:/Users/User-PC/Downloads/Thank%20you%20email/thankyou.html\"><span align=\"center\">Click here to view in browser</span></a>"
                    + "  <!--[if IE]><div class=\"ie-container\"><![endif]-->\n"
                    + "  <!--[if mso]><div class=\"mso-container\"><![endif]-->\n"
                    + "  <table style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #ffffff;width:100%\" cellpadding=\"0\" cellspacing=\"0\">\n"
                    + "  <tbody>\n"
                    + "  <tr style=\"vertical-align: top\">\n"
                    + "    <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\n"
                    + "    <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td align=\"center\" style=\"background-color: #ffffff;\"><![endif]-->\n"
                    + "    \n"
                    + "\n"
                    + "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
                    + "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #017ed0;\">\n"
                    + "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n"
                    + "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #017ed0;\"><![endif]-->\n"
                    + "      \n"
                    + "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\n"
                    + "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
                    + "  <div style=\"width: 100% !important;\">\n"
                    + "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n"
                    + "  \n"
                    + "<table style=\"font-family:'Open Sans',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                    + "  <tbody>\n"
                    + "    <tr>\n"
                    + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:40px 10px 19px;font-family:'Open Sans',sans-serif;\" align=\"left\">\n"
                    + "        \n"
                    + "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n"
                    + "  <tr>\n"
                    + "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\n"
                    + "      \n"
                    + "      <img align=\"center\" border=\"0\" src=\"images/image-7.png\" alt=\"Image\" title=\"Image\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 26%;max-width: 150.8px;\" width=\"150.8\"/>\n"
                    + "      \n"
                    + "    </td>\n"
                    + "  </tr>\n"
                    + "</table>\n"
                    + "\n"
                    + "      </td>\n"
                    + "    </tr>\n"
                    + "  </tbody>\n"
                    + "</table>\n"
                    + "\n"
                    + "<table style=\"font-family:'Open Sans',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                    + "  <tbody>\n"
                    + "    <tr>\n"
                    + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 10px 0px;font-family:'Open Sans',sans-serif;\" align=\"left\">\n"
                    + "        \n"
                    + "  <div style=\"color: #ffffff; line-height: 140%; text-align: center; word-wrap: break-word;\">\n"
                    + "    <p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 28px; line-height: 39.2px;\"><strong><span style=\"line-height: 39.2px; font-size: 28px;\">Thanks for being with us!</span></strong></span></p>\n"
                    + "  </div>\n"
                    + "\n"
                    + "      </td>\n"
                    + "    </tr>\n"
                    + "  </tbody>\n"
                    + "</table>\n"
                    + "\n"
                    + "<table style=\"font-family:'Open Sans',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                    + "  <tbody>\n"
                    + "    <tr>\n"
                    + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 10px 26px;font-family:'Open Sans',sans-serif;\" align=\"left\">\n"
                    + "        \n"
                    + "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n"
                    + "  <tr>\n"
                    + "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\n"
                    + "      \n"
                    + "      <img align=\"center\" border=\"0\" src=\"images/image-8.png\" alt=\"Image\" title=\"Image\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 100%;max-width: 580px;\" width=\"580\"/>\n"
                    + "      \n"
                    + "    </td>\n"
                    + "  </tr>\n"
                    + "</table>\n"
                    + "\n"
                    + "      </td>\n"
                    + "    </tr>\n"
                    + "  </tbody>\n"
                    + "</table>\n"
                    + "\n"
                    + "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
                    + "  </div>\n"
                    + "</div>\n"
                    + "<!--[if (mso)|(IE)]></td><![endif]-->\n"
                    + "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
                    + "    </div>\n"
                    + "  </div>\n"
                    + "</div>\n"
                    + "\n"
                    + "\n"
                    + "\n"
                    + "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
                    + "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #f9f9f9;\">\n"
                    + "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n"
                    + "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #f9f9f9;\"><![endif]-->\n"
                    + "      \n"
                    + "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\n"
                    + "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
                    + "  <div style=\"width: 100% !important;\">\n"
                    + "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n"
                    + "  \n"
                    + "<table style=\"font-family:'Open Sans',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                    + "  <tbody>\n"
                    + "    <tr>\n"
                    + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:28px 33px 25px;font-family:'Open Sans',sans-serif;\" align=\"left\">\n"
                    + "        \n"
                    + "  <div style=\"color: #444444; line-height: 200%; text-align: center; word-wrap: break-word;\">\n"
                    + "    <p style=\"font-size: 14px; line-height: 200%;\"><span style=\"font-size: 22px; line-height: 44px;\">Hi,</span><br /><span style=\"font-size: 16px; line-height: 32px;\">Thank you again for choosing us for your lorem ipsum dolor. </span></p>\n"
                    + "<p style=\"font-size: 14px; line-height: 200%;\"><span style=\"font-size: 16px; line-height: 32px;\">If you were happy with the efficiency of the service could I ask that you leave us some brief feedback on your experience via the link below.</span></p>\n"
                    + "  </div>\n"
                    + "\n"
                    + "      </td>\n"
                    + "    </tr>\n"
                    + "  </tbody>\n"
                    + "</table>\n"
                    + "\n"
                    + "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
                    + "  </div>\n"
                    + "</div>\n"
                    + "<!--[if (mso)|(IE)]></td><![endif]-->\n"
                    + "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
                    + "    </div>\n"
                    + "  </div>\n"
                    + "</div>\n"
                    + "\n"
                    + "\n"
                    + "\n"
                    + "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
                    + "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #f9f9f9;\">\n"
                    + "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n"
                    + "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #f9f9f9;\"><![endif]-->\n"
                    + "      \n"
                    + "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\n"
                    + "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
                    + "  <div style=\"width: 100% !important;\">\n"
                    + "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n"
                    + "  \n"
                    + "<table style=\"font-family:'Open Sans',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                    + "  <tbody>\n"
                    + "    <tr>\n"
                    + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 10px 0px;font-family:'Open Sans',sans-serif;\" align=\"left\">\n"
                    + "        \n"
                    + "<div align=\"center\">\n"
                    + "  <!--[if mso]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-spacing: 0; border-collapse: collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;font-family:'Open Sans',sans-serif;\"><tr><td style=\"font-family:'Open Sans',sans-serif;\" align=\"center\"><v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" href=\"\" style=\"height:50px; v-text-anchor:middle; width:252px;\" arcsize=\"80%\" stroke=\"f\" fillcolor=\"#4154f1\"><w:anchorlock/><center style=\"color:#FFFFFF;font-family:'Open Sans',sans-serif;\"><![endif]-->\n"
                    + "    <a href=\"\" target=\"_blank\" style=\"box-sizing: border-box;display: inline-block;font-family:'Open Sans',sans-serif;text-decoration: none;-webkit-text-size-adjust: none;text-align: center;color: #FFFFFF; background-color: #4154f1; border-radius: 40px; -webkit-border-radius: 40px; -moz-border-radius: 40px; width:auto; max-width:100%; overflow-wrap: break-word; word-break: break-word; word-wrap:break-word; mso-border-alt: none;\">\n"
                    + "      <span style=\"display:block;padding:15px 44px;line-height:120%;\"><span style=\"font-size: 16px; line-height: 19.2px;\"><strong><span style=\"line-height: 19.2px; font-size: 16px;\">Review us on Google</span></strong></span></span>\n"
                    + "    </a>\n"
                    + "  <!--[if mso]></center></v:roundrect></td></tr></table><![endif]-->\n"
                    + "</div>\n"
                    + "\n"
                    + "      </td>\n"
                    + "    </tr>\n"
                    + "  </tbody>\n"
                    + "</table>\n"
                    + "\n"
                    + "<table style=\"font-family:'Open Sans',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                    + "  <tbody>\n"
                    + "    <tr>\n"
                    + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:0px 10px 10px;font-family:'Open Sans',sans-serif;\" align=\"left\">\n"
                    + "        \n"
                    + "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n"
                    + "  <tr>\n"
                    + "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\n"
                    + "      \n"
                    + "      <img align=\"center\" border=\"0\" src=\"images/image-6.png\" alt=\"Image\" title=\"Image\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 35%;max-width: 203px;\" width=\"203\"/>\n"
                    + "      \n"
                    + "    </td>\n"
                    + "  </tr>\n"
                    + "</table>\n"
                    + "\n"
                    + "      </td>\n"
                    + "    </tr>\n"
                    + "  </tbody>\n"
                    + "</table>\n"
                    + "\n"
                    + "<table style=\"font-family:'Open Sans',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                    + "  <tbody>\n"
                    + "    <tr>\n"
                    + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:18px;font-family:'Open Sans',sans-serif;\" align=\"left\">\n"
                    + "        \n"
                    + "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"84%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px solid #d8d0d0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
                    + "    <tbody>\n"
                    + "      <tr style=\"vertical-align: top\">\n"
                    + "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
                    + "          <span>&#160;</span>\n"
                    + "        </td>\n"
                    + "      </tr>\n"
                    + "    </tbody>\n"
                    + "  </table>\n"
                    + "\n"
                    + "      </td>\n"
                    + "    </tr>\n"
                    + "  </tbody>\n"
                    + "</table>\n"
                    + "\n"
                    + "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
                    + "  </div>\n"
                    + "</div>\n"
                    + "<!--[if (mso)|(IE)]></td><![endif]-->\n"
                    + "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
                    + "    </div>\n"
                    + "  </div>\n"
                    + "</div>\n"
                    + "\n"
                    + "\n"
                    + "\n"
                    + "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
                    + "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #f9f9f9;\">\n"
                    + "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n"
                    + "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #f9f9f9;\"><![endif]-->\n"
                    + "      \n"
                    + "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\n"
                    + "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
                    + "  <div style=\"width: 100% !important;\">\n"
                    + "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n"
                    + "  \n"
                    + "<table style=\"font-family:'Open Sans',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                    + "  <tbody>\n"
                    + "    <tr>\n"
                    + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:19px 33px 40px;font-family:'Open Sans',sans-serif;\" align=\"left\">\n"
                    + "        \n"
                    + "  <div style=\"color: #272362; line-height: 140%; text-align: center; word-wrap: break-word;\">\n"
                    + "    <p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 24px; line-height: 33.6px;\">Look forward to hearing from you </span><br /><span style=\"font-size: 24px; line-height: 33.6px;\">in the near future.</span></p>\n"
                    + "  </div>\n"
                    + "\n"
                    + "      </td>\n"
                    + "    </tr>\n"
                    + "  </tbody>\n"
                    + "</table>\n"
                    + "\n"
                    + "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
                    + "  </div>\n"
                    + "</div>\n"
                    + "<!--[if (mso)|(IE)]></td><![endif]-->\n"
                    + "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
                    + "    </div>\n"
                    + "  </div>\n"
                    + "</div>\n"
                    + "\n"
                    + "\n"
                    + "\n"
                    + "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
                    + "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #272362;\">\n"
                    + "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n"
                    + "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #272362;\"><![endif]-->\n"
                    + "      \n"
                    + "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\n"
                    + "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
                    + "  <div style=\"width: 100% !important;\">\n"
                    + "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n"
                    + "  \n"
                    + "<table style=\"font-family:'Open Sans',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                    + "  <tbody>\n"
                    + "    <tr>\n"
                    + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:30px 4px 4px;font-family:'Open Sans',sans-serif;\" align=\"left\">\n"
                    + "        \n"
                    + "<div align=\"center\">\n"
                    + "  <div style=\"display: table; max-width:254px;\">\n"
                    + "  <!--[if (mso)|(IE)]><table width=\"254\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"border-collapse:collapse;\" align=\"center\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse; mso-table-lspace: 0pt;mso-table-rspace: 0pt; width:254px;\"><tr><![endif]-->\n"
                    + "  \n"
                    + "    \n"
                    + "    <!--[if (mso)|(IE)]><td width=\"32\" style=\"width:32px; padding-right: 19px;\" valign=\"top\"><![endif]-->\n"
                    + "    <table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"32\" height=\"32\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;margin-right: 19px\">\n"
                    + "      <tbody><tr style=\"vertical-align: top\"><td align=\"left\" valign=\"middle\" style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\n"
                    + "        <a href=\" \" title=\"Facebook\" target=\"_blank\">\n"
                    + "          <img src=\"images/image-5.png\" alt=\"Facebook\" title=\"Facebook\" width=\"32\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;max-width: 32px !important\">\n"
                    + "        </a>\n"
                    + "      </td></tr>\n"
                    + "    </tbody></table>\n"
                    + "    <!--[if (mso)|(IE)]></td><![endif]-->\n"
                    + "    \n"
                    + "    <!--[if (mso)|(IE)]><td width=\"32\" style=\"width:32px; padding-right: 19px;\" valign=\"top\"><![endif]-->\n"
                    + "    <table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"32\" height=\"32\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;margin-right: 19px\">\n"
                    + "      <tbody><tr style=\"vertical-align: top\"><td align=\"left\" valign=\"middle\" style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\n"
                    + "        <a href=\" \" title=\"Twitter\" target=\"_blank\">\n"
                    + "          <img src=\"images/image-1.png\" alt=\"Twitter\" title=\"Twitter\" width=\"32\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;max-width: 32px !important\">\n"
                    + "        </a>\n"
                    + "      </td></tr>\n"
                    + "    </tbody></table>\n"
                    + "    <!--[if (mso)|(IE)]></td><![endif]-->\n"
                    + "    \n"
                    + "    <!--[if (mso)|(IE)]><td width=\"32\" style=\"width:32px; padding-right: 19px;\" valign=\"top\"><![endif]-->\n"
                    + "    <table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"32\" height=\"32\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;margin-right: 19px\">\n"
                    + "      <tbody><tr style=\"vertical-align: top\"><td align=\"left\" valign=\"middle\" style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\n"
                    + "        <a href=\" \" title=\"LinkedIn\" target=\"_blank\">\n"
                    + "          <img src=\"images/image-2.png\" alt=\"LinkedIn\" title=\"LinkedIn\" width=\"32\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;max-width: 32px !important\">\n"
                    + "        </a>\n"
                    + "      </td></tr>\n"
                    + "    </tbody></table>\n"
                    + "    <!--[if (mso)|(IE)]></td><![endif]-->\n"
                    + "    \n"
                    + "    <!--[if (mso)|(IE)]><td width=\"32\" style=\"width:32px; padding-right: 19px;\" valign=\"top\"><![endif]-->\n"
                    + "    <table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"32\" height=\"32\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;margin-right: 19px\">\n"
                    + "      <tbody><tr style=\"vertical-align: top\"><td align=\"left\" valign=\"middle\" style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\n"
                    + "        <a href=\" \" title=\"Instagram\" target=\"_blank\">\n"
                    + "          <img src=\"images/image-3.png\" alt=\"Instagram\" title=\"Instagram\" width=\"32\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;max-width: 32px !important\">\n"
                    + "        </a>\n"
                    + "      </td></tr>\n"
                    + "    </tbody></table>\n"
                    + "    <!--[if (mso)|(IE)]></td><![endif]-->\n"
                    + "    \n"
                    + "    <!--[if (mso)|(IE)]><td width=\"32\" style=\"width:32px; padding-right: 0px;\" valign=\"top\"><![endif]-->\n"
                    + "    <table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"32\" height=\"32\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;margin-right: 0px\">\n"
                    + "      <tbody><tr style=\"vertical-align: top\"><td align=\"left\" valign=\"middle\" style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\n"
                    + "        <a href=\" \" title=\"YouTube\" target=\"_blank\">\n"
                    + "          <img src=\"images/image-4.png\" alt=\"YouTube\" title=\"YouTube\" width=\"32\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;max-width: 32px !important\">\n"
                    + "        </a>\n"
                    + "      </td></tr>\n"
                    + "    </tbody></table>\n"
                    + "    <!--[if (mso)|(IE)]></td><![endif]-->\n"
                    + "    \n"
                    + "    \n"
                    + "    <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
                    + "  </div>\n"
                    + "</div>\n"
                    + "\n"
                    + "      </td>\n"
                    + "    </tr>\n"
                    + "  </tbody>\n"
                    + "</table>\n"
                    + "\n"
                    + "<table style=\"font-family:'Open Sans',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                    + "  <tbody>\n"
                    + "    <tr>\n"
                    + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:23px 40px 10px;font-family:'Open Sans',sans-serif;\" align=\"left\">\n"
                    + "        \n"
                    + "  <div style=\"color: #b8b8b8; line-height: 140%; text-align: center; word-wrap: break-word;\">\n"
                    + "    <p style=\"font-size: 14px; line-height: 140%;\">Call us: 111 222 333<br />EMAIL: onlinequizapp@gmail.com <br />Address line / Full contact addreess &amp; post code goes here</p>\n"
                    + "  </div>\n"
                    + "\n"
                    + "      </td>\n"
                    + "    </tr>\n"
                    + "  </tbody>\n"
                    + "</table>\n"
                    + "\n"
                    + "<table style=\"font-family:'Open Sans',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                    + "  <tbody>\n"
                    + "    <tr>\n"
                    + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:19px 19px 0px;font-family:'Open Sans',sans-serif;\" align=\"left\">\n"
                    + "        \n"
                    + "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"91%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px solid #616888;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
                    + "    <tbody>\n"
                    + "      <tr style=\"vertical-align: top\">\n"
                    + "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
                    + "          <span>&#160;</span>\n"
                    + "        </td>\n"
                    + "      </tr>\n"
                    + "    </tbody>\n"
                    + "  </table>\n"
                    + "\n"
                    + "      </td>\n"
                    + "    </tr>\n"
                    + "  </tbody>\n"
                    + "</table>\n"
                    + "\n"
                    + "<table style=\"font-family:'Open Sans',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                    + "  <tbody>\n"
                    + "    <tr>\n"
                    + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:15px 40px;font-family:'Open Sans',sans-serif;\" align=\"left\">\n"
                    + "        \n"
                    + "  <div style=\"color: #bbbbbb; line-height: 140%; text-align: center; word-wrap: break-word;\">\n"
                    + "    <p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 12px; line-height: 16.8px;\">&copy; Online Quiz App&nbsp; |&nbsp; All Rights Reserved </span></p>\n"
                    + "  </div>\n"
                    + "\n"
                    + "      </td>\n"
                    + "    </tr>\n"
                    + "  </tbody>\n"
                    + "</table>\n"
                    + "\n"
                    + "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
                    + "  </div>\n"
                    + "</div>\n"
                    + "<!--[if (mso)|(IE)]></td><![endif]-->\n"
                    + "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
                    + "    </div>\n"
                    + "  </div>\n"
                    + "</div>\n"
                    + "\n"
                    + "\n"
                    + "    <!--[if (mso)|(IE)]></td></tr></table><![endif]-->\n"
                    + "    </td>\n"
                    + "  </tr>\n"
                    + "  </tbody>\n"
                    + "  </table>\n"
                    + "  <!--[if mso]></div><![endif]-->\n"
                    + "  <!--[if IE]></div><![endif]-->\n"
                    + "</body>\n"
                    + "\n"
                    + "</html>", "text/html");
            //send the message
            Transport.send(mess);

            test = true;

        } catch (Exception e) {
            e.printStackTrace();
        }

        return test;
    }
}
